In [55]:
#  Solving Sudoku using backtracking algorithm

import numpy as np

# function to check the possibility of a number to be at a place
def possibility(row, col, n, mtx):
    # checking if the number is present in the current row
    for i in range(0,9):
        if mtx[row][i] == n:
            return False
        
    # checking if the number is present in the current column
    for i in range(0,9):
        if mtx[i][col] == n:
            return False
    
    # calculating 3x3 grid 
    xx = (col//3)*3
    yy = (row//3)*3
    
    # checking if the number is present in the 3x3 grid
    for i in range(0,3):
        for j in range(0,3):
            if mtx[yy+i][xx+j] == n:
                return False
    return True    

# using backtracking to solve sudoku in this function
def sudoku(mtx):
    for i in range(0,9):
        for j in range(0,9):
            if mtx[i][j] == 0:
                for n in range(1,10):
                    if possibility(i,j,n,mtx):
                        mtx[i][j] = n
                        sudoku(mtx)
                        mtx[i][j] = 0
                return
    print(np.matrix(mtx))
    print("Sudoku Solved!!!")

# enter the sudoku grid here
mtx = [[0,0,0,8,0,0,0,0,0],
       [7,8,9,0,1,0,0,0,6],
       [0,0,0,0,0,6,1,0,0],
       [0,0,7,0,0,0,0,5,0],
       [5,0,8,7,0,9,3,0,4],
       [0,4,0,0,0,0,2,0,0],
       [0,0,3,2,0,0,0,0,0],
       [8,0,0,0,7,0,4,3,9],
       [0,0,0,0,0,1,0,0,0]]

sudoku(mtx)

[[1 6 5 8 4 7 9 2 3]
 [7 8 9 3 1 2 5 4 6]
 [4 3 2 5 9 6 1 7 8]
 [2 9 7 4 6 3 8 5 1]
 [5 1 8 7 2 9 3 6 4]
 [3 4 6 1 5 8 2 9 7]
 [9 7 3 2 8 4 6 1 5]
 [8 2 1 6 7 5 4 3 9]
 [6 5 4 9 3 1 7 8 2]]
Sudoku Solved!!!
